### ISSUE TITLE
Compatibility with WPGraphQL V1.0 - FormFieldConnectionResolver missing methods

### ISSUE THREAD

**Issue by lqze** [harness-software/wp-graphql-gravity-forms#26] opened 2020-12-10 01:55 UTC
Hello,

Just wanting to confirm if anyone here has confirmed this plugin to be working with WPGraphQL V1.0+?

On V1.0, fatal PHP errors are caught when trying to query and `fields` on a form.

```
Class WPGraphQLGravityForms\\Connections\\FormFieldConnectionResolver contains 3 abstract methods and must therefore be declared abstract or implement the remaining methods (WPGraphQL\\Data\\Connection\\AbstractConnectionResolver::get_loader_name, WPGraphQL\\Data\\Connection\\AbstractConnectionResolver::get_ids, WPGraphQL\\Data\\Connection\\AbstractConnectionResolver::is_valid_offset) in /var/www/vhosts/mysite.com.au/httpdocs/web/app/plugins/wp-graphql-gravity-forms/src/Connections/FormFieldConnectionResolver.php on line 8, referer: https://mysite.com.au/wp/wp-admin/admin.php?page=graphiql-ide
```

**Comment by danielr18** [comment] 2021-01-10 18:28
Probably a duplicate of https://github.com/harness-software/wp-graphql-gravity-forms/issues/15

I had the same issue because I installed the zip in the release, can be fixed by downloading the master branch as ZIP, and installing it.

**Closed** 2021-01-16 08:49 UTC
